### ISSUE TITLE
Gettting `could not determine kind of name` ZMQ related errors

### ISSUE THREAD

**Issue by carlisia** [gophergala2016/gophernotes#24]
Hi @dwhitena, I ran into an issue, haven't been able to load the Go kernel yet, this might be the reason:

☻  go get github.com/gophergala2016/gophernotes                    
\# github.com/gophergala2016/gophernotes/Godeps/_workspace/src/github.com/alecthomas/gozmq
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP

I believe I have successfully followed all of the instructions with the exception of the messages above. gophernotes is listed under my `bin` directory. But when I open the gophernotes notebook, there is no Go kernel.

Could this be the reason and, if so, how to resolve it?

**Comment by dwhitena** [comment]
Hi @carlisia!  Thanks for trying out the notebook.  What version of ZeroMQ do you have?  Also, did you modify the Jupyter `kernel.json` file?  If so, could you copy the contents here?

**Comment by carlisia** [comment]
Check this out:
```
☻  brew install zeromq22                                                                           
Warning: homebrew/versions/zeromq22-2.2.0 already installed
```

```
{
    "argv": [
    	"/Users/carlisiacampos/.gvm/pkgsets/go1.5.1/global/go/bin/gophernotes",
    	"{connection_file}"
    	],
    "display_name": "Golang",
    "language": "go",
    "name": "go"
}
```

**Comment by carlisia** [comment]
Oops, the path is wrong!

**Comment by carlisia** [comment]
Ok, fixed the path (there was an extra `go` in there) but still the same.

**Comment by carlisia** [comment]
Not the kernel.json file looks like this:
```
{
    "argv": [
    	"/Users/carlisiacampos/.gvm/pkgsets/go1.5.1/global/bin/gophernotes",
    	"{connection_file}"
    	],
    "display_name": "Golang",
    "language": "go",
    "name": "go"
}
```

**Comment by dwhitena** [comment]
Can you run the gophernotes binary in a terminal, just as `gophernotes`?  Any output?  Also, what version of Jupyter?

**Comment by carlisia** [comment]
```
☻  gophernotes --help              
Usage of gophernotes:
  -autoimport
    	formats and adjusts imports automatically
  -context string
    	import packages, functions, variables and constants from external golang source files
  -debug
    	Log extra info to stderr
  -pkg string
    	specify a package where the session will be run inside

~GOPATH/src/github.com/gophergala2016/gophernotes
☻  jupyter --version         
4.1.0
```

**Comment by dwhitena** [comment]
If you run gophernotes without the `--help` do you get any output?  Also, you could try putting the kernel file under `$HOME/.ipython/kernels`.

**Comment by carlisia** [comment]
```
☻  gophernotes         
2016/05/01 15:29:30 Need a command line argument for the connection file.
```

I'll try placing the kernel file in that dir.

**Comment by dwhitena** [comment]
Yeah try `~/.ipython/kernels/gophernotes` instead of `~/.local/share/jupyter/kernels/gophernotes`

**Comment by carlisia** [comment]
Sorry, got side-tracked.

OMG it works! So awesome. Thank you.
