### ISSUE TITLE
Golang not appearing as an available kernel (possibly related to migrated ipython installation)

### ISSUE THREAD

**Issue by matthewmcneely** [gophergala2016/gophernotes#25]
Environment: OSX 10.11.4, python 2.7.11, jupyter 4.1.0 installed via anaconda 4.0.0

My ~/.jupyter folder contains a single file named migrated, which I think was created when I installed anaconda (I had ipython previously installed).

Fix: Not until I copied the kernel.json file to my _~/.ipython_ directory (as opposed to ~/.local/share...) did the Golang kernel appear as an option under "New".

```
mkdir ~/.ipython/kernels/gophernotes
cp -r $GOPATH/src/github.com/gophergala2016/gophernotes/kernel/* ~/.ipython/kernels/gophernotes/
```

**Comment by m3at** [comment]
Saw the same problem on OSX 10.11, no anaconda.
Was fixed by following your steps

**Comment by dwhitena** [comment]
Thanks @m3at and @matthewmcneely!  I will modify the README accordingly.

**Comment by dwhitena** [comment]
@m3at @matthewmcneely sorry this took a while.  Is the revised README accurate according to what you experienced?

**Comment by m3at** [comment]
Yes LGTM, thanks

**Comment by dwhitena** [comment]
Ok, closing this.  Thanks!
