### ISSUE TITLE
Can't reach the local site

### ISSUE THREAD

**Issue by djui** [gophergala2016/gophernotes#6]
```
$ docker run --name gophernotes --net host -it dwhitena/gophernotes:latest
[I 09:52:12.780 NotebookApp] Copying /.ipython/kernels -> /.local/share/jupyter/kernels
[I 09:52:12.790 NotebookApp] Writing notebook server cookie secret to /.local/share/jupyter/runtime/notebook_cookie_secret
[I 09:52:12.860 NotebookApp] Serving notebooks from local directory: /
[I 09:52:12.860 NotebookApp] 0 active kernels
[I 09:52:12.860 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 09:52:12.860 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:52:12.860 NotebookApp] No web browser found: could not locate runnable browser.
```
and when stopping:
```
^C[I 09:53:45.030 NotebookApp] interrupted
Serving notebooks from local directory: /
0 active kernels
The IPython Notebook is running at: http://localhost:8888/
Shutdown this notebook server (y/[n])? ^C[C 09:53:46.720 NotebookApp] received signal 2, stopping
[I 09:53:46.720 NotebookApp] Shutting down kernels
```

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

I assume it's because the NotebookApp tries to find its own server by pinging localhost, which on OS X using `boot2docker` or `dlite` does not make sense as the guest's container runs inside a VM rather the host.

**Comment by dwhitena** [comment]
There is not a browser installed in the container, but it should run the notebook server on port 8888 of localhost because that port is exposed by the container.  You should be able to run the container as a daemon (with the `-d` flag). Then navigate to `localhost:8888` in your browser.  See the docker installation instructions in the README for the docker command.

**Comment by djui** [comment]
I guess I was misunderstood. I tried to reach the notebook, but as OSX Docker installation are not running on localhost but rather in a VM the IP is different, and the log output indicates it tries to verify something by pinging localhost:8888; see `no web browser found. Could not locate runnable browser`. Neither interactive nor daemonized work.

**Comment by djui** [comment]
I will close this issue for now. This has to be something wrong on my side, as I can curl it from within the container. Still very strange as it's the first time I encounter this.

**Comment by dwhitena** [comment]
Thanks for the clarification @djui.  That makes more sense.  Did you try visiting the VM's IP at port 8888?  Maybe the VM is not exposing that port? 

Another option is installing locally on the VM.  Is it possible for you to install Jupyter directly on the VM and then follow the local install instructions?

Sorry for the difficulties and let me know what happens!

**Comment by djui** [comment]
Yes, curling from within the guest VM works fine. So I think it has to do with how and which address the Tornado server is binding (e.g. localhost vs 0.0.0.0 might make some sense). For example, I can run a simple Python server or [this tornado example](https://github.com/mfussenegger/docker-tornado-crate-demo) perfectly fine. So there must be something unusual with how the Anaconda images was build.

I did install it locally, but just the libzmq dependency installs more dependencies on my system that I want  to keep around, therefore I think the Dockerized version is a nice tidy alternative.

**Comment by dwhitena** [comment]
Hmmm.. Yeah, makes sense.  And yes, I love how docker keeps everything tidy.  I was already thinking I would redo the docker images because it is a little big and not very downloaded friendly.  When I do that I will look a little more into this issue and test on a VM.  Let me know if you figure anything out.

**Comment by djui** [comment]
Sorry for the spamming, found the solution, like I thought. The following works:

```
$ docker run -d dwhitena/gophernotes jupyter notebook --ip=0.0.0.0
```

Test:
```
$ curl -i http://docker.local:8888
HTTP/1.1 302 Found
Date: Sun, 07 Feb 2016 21:55:33 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: /tree
Server: TornadoServer/4.3
```

I assume this should be an issue with all OSX Docker Machine / Dlite users. So if you can reproduce this, please add a hint to the README if you think it's appropriate.

**Comment by dwhitena** [comment]
Thanks @djui.  Added to the README.

**Comment by P1xt** [comment]
I'm experiencing the same issue on both Windows 10 and Ubuntu 14.04 using the docker install.

By the same issue I mean: nothing on localhost:8888 and error messages in the log file pertaining to "no web browser found".

I managed to get it running finally by using the command:
docker run --net host -d dwhitena/gophernotes jupyter notebook --no-browser --ip=0.0.0.0

Using that command I can browser to <my docker IP>:8888 and there's a Jupyter install available. I can create Python notebooks and everything runs perfectly. However, if I create a golang notebook, whenever I attempt to run (perfectly correct) code from one of the code blocks, it tells me the kernel's dead and restarts the kernel.

I can create a separate ticket if need be though the --no-browser flag was integral to getting it to run under docker for me (which seems at least tangentially related to this ticket).

Here's what I'm seeing:
![kernel-restart](https://cloud.githubusercontent.com/assets/322175/13832083/9bccfd66-eba6-11e5-9b8c-5f909664aa96.png)

**Comment by dwhitena** [comment]
@P1xt Thanks for trying out the notebook and contributing feedback!  I think your issue is actually the same as described here: https://github.com/gophergala2016/gophernotes/issues/15

Because the notebook is interactive you don't need to define `package main` or a `function main`.  This will currently result in an error.  The intention is to code interactively without needing to do such things as shown in the examples:

https://github.com/gophergala2016/gophernotes/tree/master/examples

Could you try something without those definitions to see if it works.  Just something like is in the examples or even just `1+1` or `test := "test"`.  These should evaluate independently without defining a package or function.  All that being said, we need to add some handling for times when package main or function main are defined within the notebook.

Also, note that imports are handled in the notebook via `:import`.  See the README for more information on those commands.

**Comment by dwhitena** [comment]
@P1xt Also, good to know about the --no-browser flag.  I will add this to the docs.

**Comment by P1xt** [comment]
@dwhitena Brilliant! Once I fixed the import and yanked out the function and package definitions it worked perfectly! I'm so sorry for not reading through the examples more closely.

And yes, the "no-browser" flag was instrumental in getting it setup.

Very nice work, btw, thank you for making jupyter notebooks work for golang - it's immensely helpful.

**Comment by dwhitena** [comment]
@P1xt Awesome! Great to hear.   Like I said, we should work on a way to handle that error.  

Thanks for the feedback and I hope you enjoy it.  Any more feedback or other issues are appreciated, and I hope this helps some people in their work/play.

**Comment by sudoliyang** [comment]
Sorry i am a beginner in docker ,
I try to using docker with this,but i try to follow the README.
but it doesn't work i have no idea to  resolve this  issue.

```
＄ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

When i run i cant enter lcoalhost:8888
 ```
$ docker run --net host -d dwhitena/gophernotes jupyter notebook --no-browser --ip=0.0.0.0
360b93e63272ec33ce4885bfb712986d0425cf920df15d23a4c4c211b547494e
$ curl -i http://localhost:8888
curl: (7) Failed to connect to localhost port 8888: Connection refused
$ curl -i http://docker.local:8888/
curl: (6) Could not resolve host: docker.local
```

Thank you for ur reading.

**Comment by P1xt** [comment]
Try running docker in the terminal and see if it mentions an IP address in the startup text - this is what worked for me, localhost didn’t work but docker actually told me what IP to use when it fired up.

**Comment by sudoliyang** [comment]
@P1xt  Yes, i running docker in my iTerm2 (zsh)
but i found a solution about this issue 
I see my docker-machine setting 
```
$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/Liyang/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $(docker-machine env default
```

and i can using the notebook !
```
 $ curl -i 192.168.99.100:8888
HTTP/1.1 302 Found
Date: Sat, 19 Mar 2016 11:05:11 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: /tree
Server: TornadoServer/4.3
```)

**Comment by P1xt** [comment]
@sudoliyang Awesome! 

I was right where you are in the process a couple days ago. Two notes: you don't need a package or main function declaration and you need to use ":import" (with a colon) instead of "import".

**Comment by sudoliyang** [comment]
@P1xt  OK , Thank you for your help !  😃
